#!/usr/bin/env python3
#
#  This file is part of os-installer
#
#  Copyright 2013-2021 Solus <copyright@getsol.us>.
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 2 of the License, or
#  (at your option) any later version.
#

import logging
import os
import sys
from typing import NamedTuple

from os_installer2 import SOURCE_FILESYSTEM
from os_installer2.application import InstallerApplication
from os_installer2.permissions import PermissionsManager


class Check(NamedTuple):
    passed: bool
    error_msg: str


if __name__ == "__main__":
    logging.getLogger().setLevel(logging.DEBUG)
    logging.basicConfig(format="%(levelname)s: %(message)s")

    checks = [
        Check(os.geteuid() == 0, "You must be root to use OsInstaller"),
        Check(os.path.exists(SOURCE_FILESYSTEM), "Source file system is missing"),
    ]
    if checks[0].passed:
        # Immediately drop permissions before we init GTK.
        # We don't want to run the GTK part of os-installer with root privileges.
        PermissionsManager().down_permissions()
    fatal = None
    for check in checks:
        if not check.passed:
            fatal = check.error_msg
            break

    app = InstallerApplication(fatal)
    exit_code = app.run(sys.argv)
    sys.exit(-1 if fatal else exit_code)
